# Generated by Django 5.2.3 on 2025-07-10 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Produto')),
                ('codigo_barras', models.CharField(max_length=20, unique=True, verbose_name='Código de Barras (EAN/GTIN)')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Unitário')),
                ('fornecedor', models.CharField(blank=True, max_length=200, verbose_name='Fornecedor')),
                ('numero_nf', models.CharField(blank=True, max_length=40, verbose_name='Número da NF')),
                ('data_nf', models.DateField(blank=True, null=True, verbose_name='Data da NF')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
