# Generated by Django 5.2.3 on 2025-07-22 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovimentacaoFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], max_length=10, verbose_name='Tipo')),
                ('data', models.DateField(verbose_name='Data')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('descricao', models.CharField(blank=True, max_length=255, verbose_name='Descrição')),
                ('produto_nome', models.CharField(blank=True, max_length=200, verbose_name='Produto')),
                ('numero_nf', models.CharField(blank=True, max_length=40, verbose_name='Número da NF')),
                ('fornecedor_cliente', models.CharField(blank=True, max_length=200, verbose_name='Fornecedor/Cliente')),
            ],
        ),
    ]
